name: Deploy Hospital Management System


on:
  push:
    branches: [ main ]   # trigger on push to main branch
  workflow_dispatch:     # allow manual trigger

jobs:
  deploy:
    runs-on: self-hosted   # uses your server as the runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Docker image
        run: docker build -t hospital-app:latest .

      - name: Stop and remove old container (if exists)
        run: |
          docker stop hospital-app || true
          docker rm hospital-app || true

      - name: Run new container
        run: docker run -d --name hospital-app --network hospital-net -p 8080:80 -e DB_HOST="${{ secrets.DB_HOST }}" -e DB_USER="${{ secrets.DB_USER }}" -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" -e DB_NAME="${{ secrets.DB_NAME }}" hospital-app:latest
      - name: Clean up old images
        run: docker image prune -f
